Fe template refactor
communitiesuk/funding-service-design-post-award-submit pull request #86
Opened 2023-11-07 14:43 UTC by bobbi-hbrown

Replacement PR for https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/84 due to tagging issues

2023-11-07 15:03 UTC, Connor-OS approved these changes
All good, once this has passed QA

2023-11-08 09:40 UTC, Connor-OS requested changes
Almost there

2023-11-08 09:40 UTC, Connor-OS commented on app/templates/main/validation-errors.html
> +            <p class="govuk-body">Fix these errors and re-upload your return.</p>
This line is "The following errors have been found in your return." on main atm. The content here is what design are asking us to change too. I think the idea for this PR is to maintain all functionality from the current test env

2023-11-08 10:29 UTC, Connor-OS approved these changes
Good to go 👍

2023-11-08 14:20 UTC, cyrusdobbs commented
Can this be merged with squash when it's merged 👍

2023-11-09 10:27 UTC, merged